# netlify.toml - Codice Definitivo

[build]
  base    = "frontend"
  publish = "."
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://porcinicast-v25-api.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
