# netlify.toml

[build]
  base    = "frontend"   # Netlify guarda SOLO la cartella /frontend
  publish = "."          # pubblica /frontend
  command = ""           # nessun build

[[redirects]]
  from = "/api/*"
  to   = "https://porcinicast-v25.onrender.com/api/:splat"
  status = 200
  force  = true

# (facoltativo) header di sicurezza: puoi lasciarli
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
