services:
  - type: web
    name: porcinicast-v25-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      # === API KEYS (aggiorna con le tue) ===
      - key: OPENWEATHER_API_KEY
        value: "2bdef99f19b45ae8df83062ea6ed5848"
      - key: CDS_API_KEY
        value: "b9bd9c49-99a6-40d9-81bb-f96f10aafe3b"
      - key: CDS_API_URL
        value: "https://cds.climate.copernicus.eu/api"
      - key: NOMINATIM_EMAIL
        value: "thejampy4@gmail.com"
    healthCheckPath: /api/health
    
    # Storage persistente per database
    disk:
      name: porcini-data-v25
      sizeGB: 1
      mountPath: /app/data